### ISSUE TITLE
What were your go-to websites/books/courses while you were learning to code? 

### ISSUE THREAD

**Issue by rmorabia** [taniarascia/ama#1]

**Comment by taniarascia** [comment]
I’ll be completely honest - I have not used very many learning resources at all. Most of my learning has come from trial and error and cobbling things together. When it comes to HTML and CSS, I never read any resources at all.

However, as I began learning programming, I delved into a few books and free resources here and there, and there are a few that I found extremely helpful.

My first introduction to JavaScript was [A Smarter Way to Learn JavaScript](https://www.amazon.com/Smarter-Way-Learn-JavaScript-technology-ebook/dp/B00H1W9I6C), and I think it is hands down the best introduction to any programming language I’ve ever found. If someone has never touched code beyond HTML and CSS, this is what I would recommend for them to read first.

As a next step, I would consider going through the free [Practical JavaScript](https://watchandcode.com/) course to learn how to take all that information and actually build something.

Finally, I think everyone should learn the command line, and I did so through the [Command Line Crash Course](https://learnpythonthehardway.org/book/appendixa.html). Although I didn’t continue on the rest of his series, learning the command line was essential and changed the way I viewed everything.

At this point, those are the only resources I can highly recommend. A few that I found actively unhelpful for new developers are PHP The Right Way and Eloquent JavaScript, two that are very often recommended.

**Comment by thereisnowinter** [comment]
> When it comes to HTML and CSS, I never read any resources at all.

Hello, Thanks for your answer. 
since you never read any resources at all, how did you learn CSS ? I am really struggle in learning CSS, there are too many things need to memorize.
