### ISSUE TITLE
Learning JS, what concept(s) are you struggling / did you struggle with the most?

### ISSUE THREAD

**Issue by tstelzer** [taniarascia/ama#10]
For example for me this was using functions as arguments to other functions. Blew my mind when I finally got it.

**Comment by taniarascia** [comment]
That is an amazing question, Timm. JavaScript has been a huge struggle for me overall, as it was and is the first programming language I've taught myself - after the relative simplicity of learning the markup and style languages of HTML and CSS. I feel confident that I'll become fluent, having taught myself to speak and get by in various human languages, which are infinitely more complex and nuanced (though a bit more forgiving of error).

First, the absolute basics of syntax. Now, I can scan a JavaScript file and have a basic idea of what's going on in an instant - loops there, variables there, functions here. The first time I saw even a line of JavaScript, it was all a mystery. Just getting to the point where everything looked familiar and not be completely programming illiterate was my first huge struggle.
 Secondly, the DOM. The DOM is a concept that is very integrated with JavaScript, and it can be hard to separate the programming language from the DOM API when you're a beginner. The first time I typed `document` into the console changed my life. When I realized `getElementById()` can literally just be returning an HTML string. The first time I submitted a file somewhere via ajax was mind-blowing. The first time I changed the stylesheet of a page with the click of a button, it was huge.

I learned how to work with jQuery before working with plain JavaScript, and I don't regret that. It broke the barrier to entry and allowed me to do simple things like toggle a dropdown or a menu.

Figuring out how to work with JSON and JavaScript together to access APIs was also huge. I'm no longer limited to the static data that I input, but I can work with any data from any public source.
 Getting Node.js and npm set up was one of the biggest struggles I've ever been through, which was just to use Grunt and Gulp and later Webpack to run tasks and take care of other processes. When I figured out how the whole local `node_modules` system works, everything really clicked. 

My current struggle with JavaScript is learning how to work with frameworks and libraries to build apps. I need to learn authentication, how to build REST APIs, how to do anything in React, the concept of state and MVC, and how Promises and async/await work and why I need them, to mention a few.
