### ISSUE TITLE
Web server monitoring

### ISSUE THREAD

**Issue by ks7000** [taniarascia/ama#15]
What do you think about web server monitoring?
I mean, should we write code that lightens the load on the servers?
For example, many sites only show the images when one is moved to that location or when the mouse is on top of the image.
Your opinion, please.

**Comment by taniarascia** [comment]
Hi there,

Of course it’s important to keep an eye on the performance of your server, and see where there might be any inefficient code draining resources or slowing the site down.

I tend to attempt to make pages that are not too image and JavaScript heavy. I’ve personally never implemented “lazy loading” images and the like, but I’ve simply never worked on any sites resource intensive enough to justify it. I run my site through a few page speed tests, edit what I can, and put it behind a CDN.

Monitoring performance is important, but it’s easy to get obsessed with trying to get perfect speed scores, which is often not necessary.
