### ISSUE TITLE
Any thoughts on how web interaction will translate to immersive technologies?

### ISSUE THREAD

**Issue by joshkemmer** [taniarascia/ama#16]
AR, VR, AI, internet of things, etc... Do you have any specific thoughts/speculation on how we'll eventually be interacting with the web in light of these emerging technologies? Does this mean a paradigm shift for our daily processes as developers?

**Comment by taniarascia** [comment]
Wow Josh, great question! I wish I had more insight or experience so I could give you a better answer. I feel like you’re spot on with predicting a paradigm shift for the processes of daily developers, but when that will happen, I don’t have the slightest clue. 

Technology keeps advancing exponentially, though a lot of things under the hood of the web have remained relatively the same, even if the way we interact with it is very different.

Personally, my only experience with VR is playing a bit of PlayStation VR (which is awesome, by the way) and my only experience with AI is arguing with Slackbot. 

I was thinking about trying to bring back Webrings the other day, so clearly I’m not the right person to ask when it comes to the future.
