### ISSUE TITLE
How do I learn to make CSS components? 

### ISSUE THREAD

**Issue by jaredallay** [taniarascia/ama#19]
Hey Tania,

I believe I'm too reliant on front-end frameworks, yet I'm struggling to code my own CSS components (i.e. buttons, cards, hero images, etc.). What resources would you recommend to learn how to make my own CSS components and not tie myself down to what front-end frameworks offer? 

Thanks a lot, 

Jared

**Comment by taniarascia** [comment]
Great question, and you know I got you covered.

[Styling UI Components from Scratch: Buttons and Forms](https://www.taniarascia.com/styling-ui-components-from-scratch-buttons-forms/)

This is a hidden gem on my site, and it'll teach you to do just that. [Here is one](https://www.taniarascia.com/design-for-developers) I made for cards. And of course, [You Don't Need a Framework: Understanding the Fundamentals of Responsive Design](https://www.taniarascia.com/you-dont-need-a-framework/).
