### ISSUE TITLE
Do you prefer to work on real-life projects before getting a good grasp of a language or the other way round?

### ISSUE THREAD

**Issue by mrassili** [taniarascia/ama#2]
I personally learn by doing something I am uncomfortable with. It forces me to grow and horn everything I learn.

**Comment by taniarascia** [comment]
It's a little bit of both, but I tend towards working on real-life projects and supplementing that with some technical knowledge on the side.

I find it very similar to learning an instrument. It would be hard to get very far without learning the names of the notes or a couple of chords and scales, but if all you do is learn music theory and you don't learn how to play any songs that you like, you will most likely lose interest and stop practicing.

The same goes for code. The most important thing is to work on actual projects that are fun for you, but cementing what you've learned with some technical knowledge will go a long way.
