### ISSUE TITLE
What music do you listen to while working?

### ISSUE THREAD

**Issue by misterorion** [taniarascia/ama#3]

**Comment by taniarascia** [comment]
Great question! This varies quite a bit, but I have my staples. 

One of my absolute favorite things to listen to while coding is orchestrated or piano versions of video game music. There are no lyrics to distract me and the music is beautiful and familiar. Final Fantasy music in particular. The artist TPR has melancholy versions of all the soundtracks, and Distant Worlds is the FF orchestra.

Aside from that, I make a lot of playlists. Sometimes I’ll listen to an 80s or 90s playlist, but most often I listen to a variety of 2010s indie/alternative. This can include bands like Reign of Kindo, Arcade Fire, Two Door Cinema Club, Miami Horror, Savor Adoire, and all sorts of bands that I just randomly discover by making a station from a song I like.

The Amelie soundtrack is great, as I have a penchant for accordion music. I also enjoy the Scottish subdued post-rock movement like Mogwai.

So there’s a very short list of a few of my eclectic musical choices for coding.
